export const assetsUrl = 'assets'
export const mimeExtension = '.svg'
export const assetsMimeUrl = `${assetsUrl}/mimes`
export const mimeFile = 'file'
export const mimeDirectory = 'directory'
export const mimeDirectoryShare = 'directory_share'
export const mimeDirectorySync = 'directory_sync'
export const mimeDirectoryDisabled = 'directory_disabled'
export const mimeDirectoryError = 'directory_error'

export function getAssetsMimeUrl(asset: string): string {
  return `${assetsMimeUrl}/${asset}${mimeExtension}`
}

export const logoIconUrl = `${assetsUrl}/favicon${mimeExtension}`
export const logoDarkUrl = `${assetsUrl}/logo-dark${mimeExtension}`
export const logoUrl = `${assetsUrl}/logo${mimeExtension}`
export const linkProtected = `${assetsUrl}/protected.png`
export const defaultMimeUrl = getAssetsMimeUrl(mimeFile)
export const MAX_TEXT_FILE_SIZE = 25 * 1024 * 1024 // 25 MB
export const COMPRESSIBLE_MIMES = new Set(['application-gzip', 'application-zip', 'application-x-tar'])
export const SHORT_MIME = {
  DOCUMENT: 'document',
  TEXT: 'text',
  MARKDOWN: 'markdown',
  IMAGE: 'image',
  MEDIA: 'media',
  PDF: 'pdf'
} as const
export const UNSUPPORTED_VIEW_EXTENSIONS = new Set([
  'rar',
  '7z',
  'zip',
  'tar',
  'tgz',
  'gz',
  'gzip',
  'bz2',
  'tbz',
  'tbz2',
  'xz',
  'txz',
  'zst',
  'zstd',
  'br',
  'lz',
  'lzma',
  'lzo',
  'iso',
  'dmg',
  'img',
  'toast',
  'vhd',
  'vhdx',
  'vdi',
  'vmdk',
  'qcow2',
  'hdd',
  'sparseimage',
  'exe',
  'com',
  'dll',
  'msi',
  'scr',
  'apk',
  'ipa',
  'appimage',
  'deb',
  'rpm',
  'pkg',
  'snap',
  'bin',
  'elf',
  'wasm',
  'class',
  'pyc',
  'pyo',
  'dex',
  'odex',
  'so',
  'o',
  'a',
  'lib',
  'sys',
  'drv',
  'cab',
  'jar',
  'war',
  'ear',
  'whl',
  'nupkg',
  'db',
  'db3',
  'sqlite',
  'sqlite3',
  'mdb',
  'accdb',
  'ttf',
  'otf',
  'woff',
  'woff2',
  'eot',
  'doc',
  'docm',
  'docx',
  'dot',
  'dotm',
  'dotx',
  'xls',
  'xlsb',
  'xlsm',
  'xlsx',
  'xlt',
  'xltm',
  'xltx',
  'ppt',
  'pptm',
  'pptx',
  'pot',
  'potm',
  'potx',
  'pps',
  'ppsm',
  'ppsx',
  'odt',
  'ods',
  'odp',
  'pages',
  'numbers',
  'key',
  'epub',
  'vsd',
  'vsdm',
  'vsdx',
  'vss',
  'vssm',
  'vssx',
  'vst',
  'vstm',
  'vstx',
  'dwg',
  'sketch',
  'fig',
  'psd',
  'ai',
  'indd',
  'blend'
])
