-- Adds the per-row CONTENT author (#491). Generated by drizzle-kit; the comment
-- is the only hand-added part.
--
-- EXISTING ROWS ARE DELIBERATELY NOT BACKFILLED, and will read as "unknown
-- author" in the version list until they are superseded by new history.
--
-- `authorId` names whoever REPLACED a row's content, so row n's true author is
-- row n-1's `authorId`. That makes the obvious backfill — a correlated
-- subquery shifting each file's rows by one — exactly the read-time shift the
-- thinning design rules out (§8): thinning removes rows, so the surviving row
-- n-1 is not necessarily the row that actually preceded n. The shift would
-- write a plausible, permanent, unverifiable lie into the column whose whole
-- purpose is to stop showing one. NULL is honest.
ALTER TABLE `custom_files_versions` ADD `contentAuthorId` bigint unsigned;--> statement-breakpoint
ALTER TABLE `custom_files_versions` ADD CONSTRAINT `custom_files_versions_contentAuthorId_users_id_fk` FOREIGN KEY (`contentAuthorId`) REFERENCES `users`(`id`) ON DELETE set null ON UPDATE no action;