mysql:
  url: 'mysql://root:MySQLRootPassword@mariadb:3306/sync_in'
auth:
  encryptionKey: 'changeEncryptionKeyWithStrongKey'
  token:
    access:
      secret: 'changeAccessWithStrongSecret'
    refresh:
      secret: 'changeRefreshWithStrongSecret'
applications:
  files:
    dataPath: /app/data
    editors:
      collabora:
        enabled: false
      onlyoffice:
        enabled: false
        secret: 'onlyOfficeSecret'
      eurooffice:
        enabled: false
        secret: 'euroOfficeSecret'
