export const RETRYABLE_CONNECTION_ERROR_CODES = new Set([
  'EAI_AGAIN',
  'ECONNABORTED',
  'ECONNREFUSED',
  'ECONNRESET',
  'EHOSTUNREACH',
  'ENETUNREACH',
  'ENOTFOUND',
  'EPIPE',
  'ER_CON_COUNT_ERROR',
  'ER_SERVER_SHUTDOWN',
  'ETIMEDOUT',
  'PROTOCOL_CONNECTION_LOST'
])
