import { SPACES_ROUTE } from '../../spaces/constants/routes'
import { FILE_OPERATION } from './operations'

export const FILES_ROUTE = {
  BASE: SPACES_ROUTE.BASE,
  OPERATION: 'operation',
  TASK_OPERATION: 'task/operation',
  TASKS: 'tasks',
  TASKS_CANCEL: 'cancel',
  TASKS_DOWNLOAD: 'download',
  TASKS_POLL: 'poll',
  RECENTS: 'recents',
  SEARCH: 'search',
  INDEXING: 'indexing',
  INDEXING_START: 'start',
  INDEXING_STOP: 'stop'
} as const

export const API_FILES_OPERATION = `${FILES_ROUTE.BASE}/${FILES_ROUTE.OPERATION}`
export const API_FILES_OPERATION_THUMBNAIL = `${API_FILES_OPERATION}/${FILE_OPERATION.THUMBNAIL}`
export const API_FILES_OPERATION_MAKE = `${API_FILES_OPERATION}/${FILE_OPERATION.MAKE}`
export const API_FILES_OPERATION_UPLOAD = `${API_FILES_OPERATION}/${FILE_OPERATION.UPLOAD}`
export const API_FILES_TASK_OPERATION = `${FILES_ROUTE.BASE}/${FILES_ROUTE.TASK_OPERATION}`
export const API_FILES_TASK_OPERATION_DOWNLOAD = `${API_FILES_TASK_OPERATION}/${FILE_OPERATION.DOWNLOAD}`
export const API_FILES_TASK_OPERATION_COMPRESS = `${API_FILES_TASK_OPERATION}/${FILE_OPERATION.COMPRESS}`
export const API_FILES_TASK_OPERATION_DECOMPRESS = `${API_FILES_TASK_OPERATION}/${FILE_OPERATION.DECOMPRESS}`
export const API_FILES_TASKS = `${FILES_ROUTE.BASE}/${FILES_ROUTE.TASKS}`
export const API_FILES_TASKS_CANCEL = `${API_FILES_TASKS}/${FILES_ROUTE.TASKS_CANCEL}`
export const API_FILES_TASKS_DOWNLOAD = `${FILES_ROUTE.BASE}/${FILES_ROUTE.TASKS}/${FILES_ROUTE.TASKS_DOWNLOAD}`
export const API_FILES_TASKS_POLL = `${API_FILES_TASKS}/${FILES_ROUTE.TASKS_POLL}`
export const API_FILES_RECENTS = `${FILES_ROUTE.BASE}/${FILES_ROUTE.RECENTS}`
export const API_FILES_SEARCH = `${FILES_ROUTE.BASE}/${FILES_ROUTE.SEARCH}`
export const API_FILES_INDEXING = `${FILES_ROUTE.BASE}/${FILES_ROUTE.INDEXING}`
export const API_FILES_INDEXING_START = `${API_FILES_INDEXING}/${FILES_ROUTE.INDEXING_START}`
export const API_FILES_INDEXING_STOP = `${API_FILES_INDEXING}/${FILES_ROUTE.INDEXING_STOP}`
